export const LOAD_FILES_SUCCESS = "LOAD_FILES_SUCCESS";
export const APPROVE_FILE_SUCCESS = "APPROVE_FILE_SUCCESS";
export const REJECT_FILE_SUCCESS = "REJECT_FILE_SUCCESS";
export const DOWNLOAD_BATCH_FILES_SUCCESS = "DOWNLOAD_BATCH_FILES_SUCCESS";